# Ejercicios Numpy

## Ejercicio 1
Hacer una matriz de 8x8 con numeros enteros consecutivos empezando en el uno, llenado por filas ([1,2,3,4])

In [1]:
import numpy as np

In [11]:
#creamos un arreglo de 64 espacios que va de 1 en 1 hasta el 64
a_1 = np.arange(1,65)
#lo reformamos a una matriz de 8x8
a_1_ayuda = a_1.reshape(8,8)
a_1_ayuda

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

## Ejercicio 2
1) Hacer una matriz de 8x8 con numeros enteros consecutivos, llenado por columnas

2) Reemplazar los elementos que tengan al menos un 3 por un -99

In [3]:
#Creamos una matriz de 8x8 con numeros consecutivos y llenada por fila
a_1 = np.arange(1,65)
a_1_ayuda = a_1.reshape(8,8)
a_1_sol = np.zeros([8,8])
#Creamos una nueva matriz que a cada elemento i,j le asigna el elemento j,i de la matriz original, de esta manera transponiendola
for i in range(8):
    for j in range(8):
        a_1_sol[i,j]=a_1_ayuda[j,i]
print(a_1_sol,"\n",a_1_ayuda)

[[ 1.  9. 17. 25. 33. 41. 49. 57.]
 [ 2. 10. 18. 26. 34. 42. 50. 58.]
 [ 3. 11. 19. 27. 35. 43. 51. 59.]
 [ 4. 12. 20. 28. 36. 44. 52. 60.]
 [ 5. 13. 21. 29. 37. 45. 53. 61.]
 [ 6. 14. 22. 30. 38. 46. 54. 62.]
 [ 7. 15. 23. 31. 39. 47. 55. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64.]] 
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [4]:
#nos movemos a a traves de la matriz y convertimos cada uno de los numeros que contiene en string, 
#analizamos si el string contiene un '3', si lo tiene reemplaza ese valor por -99 como entero
for i in range(8):
    for j in range(8):
        if '3' in str(a_1_sol[i,j]):
            a_1_sol[i,j] = -99
a_3_aux = a_1_sol
print(a_3_aux)

[[  1.   9.  17.  25. -99.  41.  49.  57.]
 [  2.  10.  18.  26. -99.  42.  50.  58.]
 [-99.  11.  19.  27. -99. -99.  51.  59.]
 [  4.  12.  20.  28. -99.  44.  52.  60.]
 [  5. -99.  21.  29. -99.  45. -99.  61.]
 [  6.  14.  22. -99. -99.  46.  54.  62.]
 [  7.  15. -99. -99. -99.  47.  55. -99.]
 [  8.  16.  24. -99.  40.  48.  56.  64.]]


## Ejercicio 3

In [1]:
import numpy as np

i) reproducir la matriz B

In [5]:
a_2 = np.arange(0,40)
a_2 = a_2/100 + .4
a_2 = a_2.reshape(8,5)
a_2#solucion del inciso i

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])

ii)Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas.

In [9]:
a_3_final = []
a_33 = []
a_3_aux = a_1_sol#es la solucion del ejercicio 2
for i in range(0,8):
    a_3_final.append(i)  #creamos una lista de 8 elementos  
for i in range(0,8):
    a_3_final[0] = np.append(a_3_aux[i],a_2[i,0])#al primer elemento de una lista de 8 elementos le asignamos la primer fila 
    #de la solucion del ejercicio 2 y le agregamos el primer elemento de la fila 1 de la solucion del primer inciso
    for j in range(1,5):
        a_3_final[j] = np.append(a_3_final[j-1],a_2[i,j])#en el 2do elemento de la lista guardamos una copia del primer elemento 
        #de la lista y le agregamos el segundo elemento de la fila 1 de la solucion del primer inciso, y repetimos este proceso  
        #para todos los elementos de la primera fila, despues repeteimos para los de la 2da fila etc
    a_33.append(a_3_final[j]) #en otra lista vacia, agregamos el arreglo final de los 2 renglones concatenados
a_33 = np.concatenate(a_33).reshape(8,13) #concatenamos todos los elementos de la lista y los reformamos
a_33#solucion del inciso ii

array([[  1.  ,   9.  ,  17.  ,  25.  , -99.  ,  41.  ,  49.  ,  57.  ,
          0.4 ,   0.41,   0.42,   0.43,   0.44],
       [  2.  ,  10.  ,  18.  ,  26.  , -99.  ,  42.  ,  50.  ,  58.  ,
          0.45,   0.46,   0.47,   0.48,   0.49],
       [-99.  ,  11.  ,  19.  ,  27.  , -99.  , -99.  ,  51.  ,  59.  ,
          0.5 ,   0.51,   0.52,   0.53,   0.54],
       [  4.  ,  12.  ,  20.  ,  28.  , -99.  ,  44.  ,  52.  ,  60.  ,
          0.55,   0.56,   0.57,   0.58,   0.59],
       [  5.  , -99.  ,  21.  ,  29.  , -99.  ,  45.  , -99.  ,  61.  ,
          0.6 ,   0.61,   0.62,   0.63,   0.64],
       [  6.  ,  14.  ,  22.  , -99.  , -99.  ,  46.  ,  54.  ,  62.  ,
          0.65,   0.66,   0.67,   0.68,   0.69],
       [  7.  ,  15.  , -99.  , -99.  , -99.  ,  47.  ,  55.  , -99.  ,
          0.7 ,   0.71,   0.72,   0.73,   0.74],
       [  8.  ,  16.  ,  24.  , -99.  ,  40.  ,  48.  ,  56.  ,  64.  ,
          0.75,   0.76,   0.77,   0.78,   0.79]])

iii) Agregar una linea al final con el promedio de cada columna

In [200]:
ax = np.zeros(8)
proms = np.zeros(13)
for j in range(0,13):
    for i in range(0,8):
        ax[i] = a_33[i,j]
    proms[j] = np.mean(ax)
a_33 = np.append(a_33,proms).reshape(9,13)
print(a_33)#solucion del inciso iii

[[  1.      9.     17.     25.    -99.     41.     49.     57.      0.4
    0.41    0.42    0.43    0.44 ]
 [  2.     10.     18.     26.    -99.     42.     50.     58.      0.45
    0.46    0.47    0.48    0.49 ]
 [-99.     11.     19.     27.    -99.    -99.     51.     59.      0.5
    0.51    0.52    0.53    0.54 ]
 [  4.     12.     20.     28.    -99.     44.     52.     60.      0.55
    0.56    0.57    0.58    0.59 ]
 [  5.    -99.     21.     29.    -99.     45.    -99.     61.      0.6
    0.61    0.62    0.63    0.64 ]
 [  6.     14.     22.    -99.    -99.     46.     54.     62.      0.65
    0.66    0.67    0.68    0.69 ]
 [  7.     15.    -99.    -99.    -99.     47.     55.    -99.      0.7
    0.71    0.72    0.73    0.74 ]
 [  8.     16.     24.    -99.     40.     48.     56.     64.      0.75
    0.76    0.77    0.78    0.79 ]
 [ -8.25   -1.5     5.25  -20.25  -81.625  26.75   33.5    40.25    0.575
    0.585   0.595   0.605   0.615]]


iv) Agregar una columna al final con el valor maximo de cada fila

In [242]:
b = a_33
lista = []
lis = []
for i in range(0,9):
    lista.append(i)
for i in range(0,9):
    a = np.max(a_33[i])
    lista[i] = np.append(b[i],a) 
lista = np.concatenate(lista).reshape(9,14)
lista #solucion del inciso iv

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,  57.   ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,  58.   ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ,  59.   ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,  60.   ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,  61.   ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,  62.   ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,  55.   ],

Otras soluciones

In [12]:
B = np.arange(0.4,0.8,0.01).reshape(8,5)

print('B = \n', B)

B = 
 [[0.4  0.41 0.42 0.43 0.44]
 [0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54]
 [0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64]
 [0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74]
 [0.75 0.76 0.77 0.78 0.79]]


In [16]:
C = np.concatenate((a_3_aux, B), axis=1)
C

array([[  1.  ,   9.  ,  17.  ,  25.  , -99.  ,  41.  ,  49.  ,  57.  ,
          0.4 ,   0.41,   0.42,   0.43,   0.44],
       [  2.  ,  10.  ,  18.  ,  26.  , -99.  ,  42.  ,  50.  ,  58.  ,
          0.45,   0.46,   0.47,   0.48,   0.49],
       [-99.  ,  11.  ,  19.  ,  27.  , -99.  , -99.  ,  51.  ,  59.  ,
          0.5 ,   0.51,   0.52,   0.53,   0.54],
       [  4.  ,  12.  ,  20.  ,  28.  , -99.  ,  44.  ,  52.  ,  60.  ,
          0.55,   0.56,   0.57,   0.58,   0.59],
       [  5.  , -99.  ,  21.  ,  29.  , -99.  ,  45.  , -99.  ,  61.  ,
          0.6 ,   0.61,   0.62,   0.63,   0.64],
       [  6.  ,  14.  ,  22.  , -99.  , -99.  ,  46.  ,  54.  ,  62.  ,
          0.65,   0.66,   0.67,   0.68,   0.69],
       [  7.  ,  15.  , -99.  , -99.  , -99.  ,  47.  ,  55.  , -99.  ,
          0.7 ,   0.71,   0.72,   0.73,   0.74],
       [  8.  ,  16.  ,  24.  , -99.  ,  40.  ,  48.  ,  56.  ,  64.  ,
          0.75,   0.76,   0.77,   0.78,   0.79]])

In [17]:
mean_col = np.mean(C, axis=0)
mean_col

array([ -8.25 ,  -1.5  ,   5.25 , -20.25 , -81.625,  26.75 ,  33.5  ,
        40.25 ,   0.575,   0.585,   0.595,   0.605,   0.615])

In [27]:
D = np.append(C, mean_col.reshape(1,13), axis = 0)
D

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ],
       [  8.   ,  16.   ,  24.   , -99.   ,  40.   ,  48.   , 

In [28]:
max_fila = np.max(D, axis=1)
max_fila

array([57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 55.  , 64.  , 40.25])

In [29]:
E = np.append(D, max_fila.reshape(9,1), axis = 1)
E

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,  57.   ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,  58.   ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ,  59.   ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,  60.   ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,  61.   ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,  62.   ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,  55.   ],